sudo: required

language: python

services:
  - docker

before_install:
  - docker build --tag shardingpoc .

script:
  - docker run -it --net=host --env="DISPLAY" --volume="$HOME/.Xauthority:/root/.Xauthority:rw" --volume="usr/ethshardingpoc" shardingpoc